web/__init__.py
# -*- coding: utf-8 -*-
"""Myles' GIFs."""
__version__ = '1.0.0'

web/app.py
# -*- coding: utf-8 -*-
"""The app module."""
import datetime

from flask import Flask

from web import commands
from web.views import blueprint


def create_app(config='web.config.Config'):
    app = Flask(__name__)

    app.config.from_object(config)

    app.cli.add_command(commands.freeze)
    app.cli.add_command(commands.update_index)

    app.register_blueprint(blueprint)

    @app.context_processor
    def date_processor():
        def now(strftime='%Y-%m-%dT%H:%M:%S'):
            return datetime.datetime.now().strftime(strftime)

        return dict(now=now)

    return app

web/views.py
# -*- coding: utf-8 -*-
"""Views."""
from flask import (Blueprint, abort, current_app, jsonify, render_template,
                   send_from_directory, url_for, Response)

from feedgenerator import Atom1Feed
from jsonfeed import JSONFeed

from .pagination import Paginator
from .utils import all_gifs, load_data

blueprint = Blueprint('views', __name__)


@blueprint.route('/')
@blueprint.route('/p<int:page>.html')
def gif_list(page=1):
    """List all Gifs."""
    gifs = all_gifs()

    paginator = Paginator(gifs, 25)

    page = paginator.get_page(page)

    return render_template('gif-list.html', page=page)


@blueprint.route('/api.json')
def gif_list_json():
    """List all Gifs in a JSON format."""
    gifs = all_gifs()

    return jsonify(gifs)


@blueprint.route('/feed.<string:feed_type>')
@blueprint.route('/feed-<int:page>.<string:feed_type>')
def feed(feed_type, page=1):
    if feed_type not in ['json', 'xml']:
        abort(404)

    author_info = {
        'author_name': 'Myles Braithwaite',
        'author_link': 'https://mylesb.ca/',
        'author_email': 'me@mylesb.ca'
    }

    meta_info = {
        'title': "Myles' GIFs",
        'description': 'GIF is pronounced with a soft G.',
        'link': 'https://gifs.mylesb.ca/',
        'feed_guid': 'https://gifs.mylesb.ca/',
        'language': 'en'
    }

    if feed_type == 'json':
        feed = JSONFeed(**{**meta_info, **author_info})
        mimetype = feed.content_type
    else:
        feed = Atom1Feed(**{**meta_info, **author_info})
        mimetype = 'application/atom+xml'

    gifs = all_gifs()

    paginator = Paginator(gifs, 25)

    page = paginator.get_page(page)

    if page.has_next and feed_type == 'json':
        feed.next_url = 'https://gifs.mylesb.ca{}'.format(url_for(
            'views.feed', feed_type='json', page=page.next_page_number))

    for gif in page.object_list:
        feed.add_item(
            guid=gif['html_url'],
            title=gif.get('caption', 'GIF'),
            link=gif['html_url'],
            description=('<a href="{html_url}">'
                         '<img src="{image_url}"></a>').format(**gif),
            pubdate=gif['date'],
            categories=gif.get('keywords'),
            **author_info
        )

    return Response(feed.writeString('utf-8'), mimetype=mimetype)


@blueprint.route('/<path:slug>/')
def gif_detail(slug):
    """Get detail of Gif."""
    if slug == 'favicon.ico':
        abort(404)

    gif = load_data(slug)

    return render_template('gif-detail.html', gif=gif)


@blueprint.route('/<path:slug>/image.gif')
def gif_image(slug):
    """Get the Gif."""
    return send_from_directory(current_app.config['GIFS_PATH'],
                               '{}.gif'.format(slug))


@blueprint.route('/<path:slug>/image.mp4')
def gif_image_mp4(slug):
    """Get the MP4."""
    return send_from_directory(current_app.config['GIFS_PATH'],
                               '{}.mp4'.format(slug))


@blueprint.route('/<path:slug>/image.webp')
def gif_image_webp(slug):
    """Get the WebP."""
    return send_from_directory(current_app.config['GIFS_PATH'],
                               '{}.webp'.format(slug))


@blueprint.route('/<path:slug>/api.json')
def gif_detail_json(slug):
    """Get detail of Gif in JSON."""
    gif = load_data(slug)
    return jsonify(gif)


@blueprint.route('/<path:slug>/oembed.json')
def gif_oembed_json(slug):
    """Get the Gif in oEmbed format."""
    tpl_url = 'https://gifs.mylesb.ca{}'

    data = load_data(slug)

    resp = {
        'version': '1.0',
        'type': 'photo',
        'url': tpl_url.format(url_for('views.gif_image', slug=slug)),
        'provider_name': "Myles' GIFs",
        'provider_url': 'https://gifs.mylesb.ca/',
    }

    if data:
        resp['width'] = data['width']
        resp['height'] = data['height']

    return jsonify(resp)

web/templates/base.html
<!DOCTYPE html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">

        <title>{% block title %}Myles' GIFs{%- endblock %}</title>
        <meta name="description" content="{% block description %}GIF is pronounced with a soft 'G'.{%- endblock %}">

        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

        <link rel="alternate" type="application/rss+xml" href="{{ url_for('views.feed', feed_type='xml') }}">
        <link rel="alternate" type="application/json" href="{{ url_for('views.feed', feed_type='json') }}" />

        <link href="mailto:me@mylesb.ca" rel="me">
        <link href="https://twitter.com/MylesGifs" rel="me">

        <link rel="pingback" href="https://webmention.io/gifs.mylesb.ca/xmlrpc">
        <link rel="webmention" href="https://webmention.io/gifs.mylesb.ca/webmention">

        {% block extra_head %}{%- endblock %}

        <script type="text/javascript">
            var _paq = _paq || [];
            /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
            _paq.push(['trackPageView']);
            _paq.push(['enableLinkTracking']);
            (function() {
                var u = "//piwik.mylesb.ca/";
                _paq.push(['setTrackerUrl', u + 'piwik.php']);
                _paq.push(['setSiteId', '20']);
                var d = document,
                    g = d.createElement('script'),
                    s = d.getElementsByTagName('script')[0];

                g.type = 'text/javascript';
                g.async = true;
                g.defer = true;
                g.src = u + 'piwik.js';
                s.parentNode.insertBefore(g, s);
            })();
        </script>

        <noscript><p><img src="//piwik.mylesb.ca/piwik.php?idsite=20&rec=1" style="border: 0;"></p></noscript>
    </head>

    <body id="mylesb.ca-gifs">
        <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

        {% block body %}{%- endblock %}

        {% block extra_body %}{%- endblock %}
        <script type="text/javascript" src="{{ url_for('static', filename='script.js') }}"></script>
    </body>
</html>

web/templates/gif-detail.html
{% extends "base.html" %}

{% block title %}{% if gif.caption %}{{ gif.caption }}{% elif gif.title %}{{ gif.title }}{% else %}Myles' GIFs{% endif %}{%- endblock %}

{% block extra_head %}
<link rel="alternate" type="text/javascript" href="{{ url_for('views.gif_detail_json', slug=gif.slug) }}">

<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@MylesGifs">
<meta name="twitter:creator" content="@MylesB">
<meta name="twitter:title" content="{% if gif.caption %}{{ gif.caption }}{% elif gif.title %}{{ gif.title }}{% else %}Myles' GIFs{% endif %}">
<meta name="twitter:description" content="Myles' GIFs">
<meta name="twitter:image" content="https://gifs.mylesb.ca{{ url_for('views.gif_image', slug=gif.slug) }}">

<meta property="og:type" content="website">
<meta property="og:url" content="https://gifs.mylesb.ca{{ url_for('views.gif_detail', slug=gif.slug) }}">
<meta property="og:title" content="{% if gif.caption %}{{ gif.caption }}{% elif gif.title %}{{ gif.title }}{% else %}Myles' GIFs{% endif %}">
<meta property="og:description" content="Myles' GIFs">
<meta property="og:image" content="https://gifs.mylesb.ca{{ url_for('views.gif_image', slug=gif.slug) }}">
{% if gif.width %}<meta property="og:image:width" content="{{ gif.width }}">{% endif %}
{% if gif.height %}<meta property="og:image:height" content="{{ gif.height }}">{% endif %}

<link rel="alternate" type="application/json+oembed" href="https://gifs.mylesb.ca{{ url_for('views.gif_oembed_json', slug=gif.slug) }}">
{%- endblock %}

{% block body %}
<div class="brand">
    <a href="{{ url_for('views.gif_list') }}" class="brand__link">
        Myles' GIFs
    </a>
    <span class="brand__slogan">GIF is pronounced with a <em>soft G</em>.</span>
</div>

<div class="gif-detail h-entry">
    <div class="gif-detail__wrapper">
        <div class="gif-detail__image-wrapper e-content">
            {% if gif.mp4 or gif.webp %}
            <video loop autoplay muted>
                {% if gif.mp4 %}
                <source src="{{ url_for('views.gif_image_mp4', slug=gif.slug) }}" type="video/mp4" class="gif-detail__image">
                {% endif %}
                {% if gif.webp %}
                <source src="{{ url_for('views.gif_image_webp', slug=gif.slug) }}" type="video/webp" class="gif-detail__image">
                {% endif %}
                <img src="{{ url_for('views.gif_image', slug=gif.slug) }}" class="gif-detail__image u-photo"{% if gif.caption %} alt="{{ gif.caption }}"{% endif %}>
            </video>
            {% else %}
            <img src="{{ url_for('views.gif_image', slug=gif.slug) }}" class="gif-detail__image" {% if gif.caption %}alt="{{ gif.caption }}"{% endif %} />
            {% endif %}
        </div>

        <div class="gif-detail__meta" style="display:none">
            <a class="p-name u-url" href="https://gifs.mylesb.ca{{ url_for('views.gif_detail', slug=gif.slug) }}">{% if gif.caption %}{{ gif.caption }}{% elif gif.title %}{{ gif.title }}{% else %}Myles' GIFs{% endif %}</a>
            <a rel="author" class="gif-detail__meta-author p-author h-card" href="https://mylesb.ca/">Myles Braithwaite</a>
            <time class="dt-published gif-detail__meta-published" datetime="{{ gif.date }}">{{ gif.date }}</time>
            <span class="gif-detail__meta-keywords">{% for keyword in gif.keywords %}<span class="p-category">{{ keyword }}</span>{% endfor %}</span>
        </div>
    </div>
</div>
{%- endblock body %}

web/templates/gif-list.html
{% extends "base.html" %}

{% block extra_head %}
<link rel="alternate" type="text/javascript" href="{{ url_for('views.gif_list_json') }}">
{%- endblock %}

{% block body %}
<div class="gif-list">
    {% if page.number == 1 %}
    <a href="/" class="gif-list__link gif-list__link--title">
        <div class="gif-list__link-wrapper">
            Myles' GIFs
        </div>
    </a>
    {% endif %}

    {% if page.has_previous %}
    <a href="{{ url_for('views.gif_list', page=page.previous_page_number) }}" class="gif-list__link gif-list__link--page">
        <div class="gif-list__link-wrapper">
            Previous
        </div>
    </a>
    {% endif %}

    {% for gif in page.object_list %}
    <a class="gif-list__link" href="{{ url_for('views.gif_detail', slug=gif.slug) }}" {% if gif.caption %}title="{{ gif.caption }}"{% endif %}>
        <div class="gif-list__link-wrapper">
            {% if gif.mp4 or gif.webp %}
            <video loop autoplay muted width="{{ gif.width }}" height="{{ gif.height }}" class="gif-list__video">
                {% if gif.mp4 %}
                <source src="{{ url_for('views.gif_image_mp4', slug=gif.slug) }}" type="video/mp4" class="gif-list__image">
                {% endif %}
                {% if gif.webp %}
                <source src="{{ url_for('views.gif_image_webp', slug=gif.slug) }}" type="video/webp" class="gif-list__image">
                {% endif %}
                <img src="{{ url_for('views.gif_image', slug=gif.slug) }}" class="gif-list__image"{% if gif.caption %} alt="{{ gif.caption }}"{% endif %}>
            </video>
            {% else %}
            <img src="{{ url_for('views.gif_image', slug=gif.slug) }}" class="gif-list__image" {% if gif.caption %}alt="{{ gif.caption }}"{% endif %} />
            {% endif %}
        </div>
    </a>
    {%- endfor %}

    {% if page.has_next %}
    <a href="{{ url_for('views.gif_list', page=page.next_page_number) }}" class="gif-list__link gif-list__link--page">
        <div class="gif-list__link-wrapper">
            Next
        </div>
    </a>
    {% endif %}
</div>
{%- endblock body %}

web/templates/index.html
{% extends "base.html" %}

{% block body %}
<div class="gif-list">
    {% for gif in gifs %}
    <a href="{{ url_for('views.gif', slug=gif ) }}" class="gif-list__link">
        <img src="{{ url_for('views.image_gif', slug=gif) }}" class="gif-list__image" />
    </a>
    {%- endfor %}
</div>
{%- endblock body %}

web/templates/search.html
{% extends "base.html" %}

{% block extra_head %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/instantsearch.js@2.3/dist/instantsearch.min.css">
{%- endblock %}

{% block extra_body %}
<script src="https://cdn.jsdelivr.net/npm/instantsearch.js@2.3/dist/instantsearch.min.js"></script>
{%- endblock %}

{% block body %}
<input id="search-input" placeholder="Search for gifs">

<script type="text/html" id="hit-template">
    <img src="{{{_highlightResult.gif_url.value}}}"/>
</script>
{%- endblock %}